jenkins:
  authorizationStrategy: unsecured
  numExecutors: 4
  scmCheckoutRetryCount: 2
tool:
  git:
    installations:
      - name: Default
        home: /usr/bin/git
credentials:
  system:
    domainCredentials:
      - domain:
          name: "github.com"
          description: "github.com domain"
          specifications:
            - hostnameSpecification:
                includes: "github.com,*.github.com"
        credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: ssh-github-java-meetup-key
              description: "SSH key for github access"
              privateKeySource:
                directEntry:
                  privateKey: ${ssh-github-java-meetup-key}
          - usernamePassword:
              scope: GLOBAL
              id: github
              description: "GitHub PAT"
              username: ${github-username}
              password: ${github-password}
      - domain:
          name: "docker.com"
          description: "dokcer.com domain"
          specifications:
            - hostnameSpecification:
                includes: "*.docker.com"
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: docker-hub
              description: "Docker Hub PAT"
              username: ${docker-hub-username}
              password: ${docker-hub-password}
      - credentials:
          - file:
              scope: GLOBAL
              id: kubectl-config
              description: "Kubectl config for docker-for-desktop"
              fileName: "kubectl-config-docker-for-desktop.yaml"
              secretBytes: ${kubectl-encoded-config}
jobs:
  - file: /var/jenkins_home/jcasc/jobs/meetup/java-meetup-1-build.groovy
  - file: /var/jenkins_home/jcasc/jobs/meetup/java-meetup-2-docker-image-build.groovy
  - file: /var/jenkins_home/jcasc/jobs/meetup/java-meetup-3-kubernetes-deploy.groovy
  - file: /var/jenkins_home/jcasc/jobs/meetup/java-meetup-quarkus.groovy
unclassified:
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED