jenkins:
  authorizationStrategy: unsecured
  numExecutors: 2
  scmCheckoutRetryCount: 2
tool:
  git:
    installations:
      - name: Default
        home: /usr/bin/git
credentials:
  system:
    domainCredentials:
      - domain:
          name: "github.com"
          description: "github.com domain"
          specifications:
            - hostnameSpecification:
                includes: "*.github.com"
        credentials:
          - basicSSHUserPrivateKey:
              scope: GLOBAL
              id: ssh-github-java-meetup-key
              description: "SSH key for github access"
              privateKeySource:
                directEntry:
                  privateKey: ${ssh-github-java-meetup-key}
          - usernamePassword:
              scope: GLOBAL
              id: github
              description: "GitHub PAT"
              username: ${github-username}
              password: ${github-password}
      - domain:
          name: "docker.com"
          description: "dokcer.com domain"
          specifications:
            - hostnameSpecification:
                includes: "*.docker.com"
        credentials:
          - usernamePassword:
              scope: GLOBAL
              id: docker-hub
              description: "Docker Hub PAT"
              username: ${docker-hub-username}
              password: ${docker-hub-password}
jobs:
  - script: >
      folder('meetup')
  - file: /var/jenkins_home/jcasc/jobs/meetup/java-meetup-quarkus.groovy
unclassified:
  globalDefaultFlowDurabilityLevel:
    durabilityHint: PERFORMANCE_OPTIMIZED